export const dState = {
  currentStock: null,
  currentTab: 'chip',
  _sessionCache: {
    symbol: null,
    klineData: null,
    chipRes: null,
    marginRes: null,
    holdersRes: null,
    daytradeRes: null,
    stockInfo: null,
  },
  klineData: [],
  klineStartIdx: 0,
  klineEndIdx: 0,
  klineHoverIdx: -1,
  klineIsDragging: false,
  klineDragStartX: -1,
  klineDragStartIdx: 0,
  klineIsYDragging: false,
  klineDragStartY: -1,
  klineDragStartZoom: 1.0,
  klineCanvasInited: false,
  klineMouseX: -1,
  klineMouseY: -1,
  klinePriceZoom: 1.0,
  staticDataCache: { holders: {}, brokers: {} },
  marginRatioYZoom: 1.0,
  holdersYZoom: 1.0,
  syncRAF: null,
  trackedBrokerName: null,
  currentBranchesLabels: [],
};
